// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: emiter.proto

package emiterService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmiterServiceClient is the client API for EmiterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmiterServiceClient interface {
	EmitUserBlocked(ctx context.Context, in *UserBlockedRequest, opts ...grpc.CallOption) (*UserBlockedResponse, error)
}

type emiterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmiterServiceClient(cc grpc.ClientConnInterface) EmiterServiceClient {
	return &emiterServiceClient{cc}
}

func (c *emiterServiceClient) EmitUserBlocked(ctx context.Context, in *UserBlockedRequest, opts ...grpc.CallOption) (*UserBlockedResponse, error) {
	out := new(UserBlockedResponse)
	err := c.cc.Invoke(ctx, "/emiter.EmiterService/EmitUserBlocked", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmiterServiceServer is the server API for EmiterService service.
// All implementations must embed UnimplementedEmiterServiceServer
// for forward compatibility
type EmiterServiceServer interface {
	EmitUserBlocked(context.Context, *UserBlockedRequest) (*UserBlockedResponse, error)
	mustEmbedUnimplementedEmiterServiceServer()
}

// UnimplementedEmiterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEmiterServiceServer struct {
}

func (UnimplementedEmiterServiceServer) EmitUserBlocked(context.Context, *UserBlockedRequest) (*UserBlockedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmitUserBlocked not implemented")
}
func (UnimplementedEmiterServiceServer) mustEmbedUnimplementedEmiterServiceServer() {}

// UnsafeEmiterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmiterServiceServer will
// result in compilation errors.
type UnsafeEmiterServiceServer interface {
	mustEmbedUnimplementedEmiterServiceServer()
}

func RegisterEmiterServiceServer(s grpc.ServiceRegistrar, srv EmiterServiceServer) {
	s.RegisterService(&EmiterService_ServiceDesc, srv)
}

func _EmiterService_EmitUserBlocked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBlockedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmiterServiceServer).EmitUserBlocked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emiter.EmiterService/EmitUserBlocked",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmiterServiceServer).EmitUserBlocked(ctx, req.(*UserBlockedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmiterService_ServiceDesc is the grpc.ServiceDesc for EmiterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmiterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emiter.EmiterService",
	HandlerType: (*EmiterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EmitUserBlocked",
			Handler:    _EmiterService_EmitUserBlocked_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emiter.proto",
}
